DALESURBAN – uDALES
DALESURBAN Program
65 statements
Source File
Uses
modmpi
modglobal
modstartup
modsave
modboundary
modthermodynamics
modsubgrid
modforces
modpois
modibm
initfac
modEB
modchecksim
modstat_nc
modfielddump
modstatsdump
Calls
Contents
Source Code
DALESURBAN
Source Code
program DALESURBAN      !Version 48
!!----------------------------------------------------------------
!!     0.0    USE STATEMENTS FOR CORE MODULES
!!----------------------------------------------------------------
  use modmpi,            only : myid, initmpi
  use modglobal,         only : rk3step,timeleft,ib,jb,kb,ke
  use modstartup,        only : startup,exitmodules
  use modsave,           only : writerestartfiles
  use modboundary,       only : boundary, grwdamp,tqaver
  use modthermodynamics, only : thermodynamics
!  use modsurface,        only : surface
  use modsubgrid,        only : subgrid
  use modforces,         only : forces,coriolis,lstend,fixuinf1,fixuinf2,fixthetainf,nudge, masscorr
  use modpois,           only : poisson
  use modibm,            only : createwalls,ibmwallfun,ibmnorm,nearwall,bottom
  use initfac,           only : readfacetfiles
  use modEB,             only : initEB,EB
!----------------------------------------------------------------
!     0.1     USE STATEMENTS FOR ADDONS STATISTICAL ROUTINES
!----------------------------------------------------------------
  use modchecksim,     only : initchecksim, checksim
  use modstat_nc,      only : initstat_nc
  use modfielddump,    only : initfielddump, fielddump,exitfielddump
  use modstatsdump,    only : initstatsdump,statsdump,exitstatsdump    !tg3315
  !use modbudget,       only : initbudget, budgetstat, exitbudget
  implicit none
!----------------------------------------------------------------
!     1      READ NAMELISTS,INITIALISE GRID, CONSTANTS AND FIELDS
!----------------------------------------------------------------
  call initmpi
  write(*,*) "done initmpi"
  call startup
  write(*,*) "done startup"
!---------------------------------------------------------
!      2     INITIALIZE STATISTICAL ROUTINES AND ADD-ONS
!---------------------------------------------------------
  call initchecksim
  call initstat_nc
  call initfielddump
  call initstatsdump !tg3315
  call readfacetfiles
  call initEB
  write(*,*) "done init stuff"
  write(6,*) 'Determine immersed walls'
  call createwalls    ! determine walls/blocks
 ! call nearwall       ! determine minimum distance and corresponding shear components, ils13 10.07.17, commented, not functional at the moment, not needed for vreman but for smag., fix in modibm
  write(6,*) 'Finished determining immersed walls'
  call boundary  !ils13 22.06.2017 inserted boundary here to get values at ghost cells before iteration starts
!  not necessary but abates the fact that temp field is randomised by randomisation of just velocity fields
!  (because advection at start of time loop without being divergence free)
!  call poisson
!------------------------------------------------------
!   3.0   MAIN TIME LOOP
!------------------------------------------------------
  write(*,*)'START myid ', myid
  do while ((timeleft>0) .or. (rk3step < 3))
    call tstep_update
!-----------------------------------------------------
!   3.2   ADVECTION AND DIFFUSION
!-----------------------------------------------------
    call advection                ! now also includes predicted pressure gradient term
    call subgrid
!-----------------------------------------------------
!   3.3   THE SURFACE LAYER
!-----------------------------------------------------
    call bottom
!-----------------------------------------------------
!   3.4   REMAINING TERMS
!-----------------------------------------------------
    call coriolis       !remaining terms of ns equation
    call forces         !remaining terms of ns equation
    call lstend         !large scale forcings
    call nudge          ! nudge top cells of fields to enforce steady-state
    call ibmwallfun     ! immersed boundary forcing: only shear forces.
    call masscorr       ! correct pred. velocity pup to get correct mass flow
    call ibmnorm        ! immersed boundary forcing: set normal velocities to zero
    call EB
    call scalsource     ! adds continuous forces in specified region of domain
!------------------------------------------------------
!   3.4   EXECUTE ADD ONS
!------------------------------------------------------
    call fixuinf2
    call fixuinf1
!-----------------------------------------------------------------------
!   3.5  PRESSURE FLUCTUATIONS, TIME INTEGRATION AND BOUNDARY CONDITIONS
!-----------------------------------------------------------------------
    call grwdamp        !damping at top of the model
    call poisson
    call tstep_integrate
    call boundary
    call fixthetainf
!-----------------------------------------------------
!   3.6   LIQUID WATER CONTENT AND DIAGNOSTIC FIELDS
!-----------------------------------------------------
    call thermodynamics
!-----------------------------------------------------
!   3.7  WRITE RESTARTFILES AND DO STATISTICS
!------------------------------------------------------
    call checksim
   ! call writedatafiles   ! write data files for later analysis
    call writerestartfiles
    call fielddump
    call statsdump        ! tg3315
  end do
!-------------------------------------------------------
!             END OF TIME LOOP
!-------------------------------------------------------
!--------------------------------------------------------
!    4    FINALIZE ADD ONS AND THE MAIN PROGRAM
!-------------------------------------------------------
  call exitfielddump
  call exitstatsdump     !tg3315
  call exitmodules
end program DALESURBAN
Call graph
dalesurban calls fixthetainf, poisson, fixuinf2, grwdamp, initstat_nc, exitstatsdump, thermodynamics, subgrid, createwalls, forces, statsdump, tstep_integrate, initeb, readfacetfiles, exitfielddump, nudge, fielddump, initstatsdump, checksim, advection, initmpi, initchecksim, tstep_update, exitmodules, bottom, ibmwallfun, scalsource, ibmnorm, boundary, writerestartfiles, coriolis, startup, fixuinf1, eb, initfielddump, masscorr, lstend
poisson calls tderive, fillps, poisr, solmpj
fixuinf2 calls detfreestream
thermodynamics calls diagfld, calthv, calc_halflev, thermo
subgrid calls diffv, closure, diffu, diffw
statsdump calls ekh, ekm, tkestatsdump, writestat_1d_nc, writestat_nc
tstep_integrate calls chem, 13
initeb calls gaussji, writestat_dims_nc, matinv4, define_nc, open_nc
readfacetfiles calls qsat, mpi_bcast, nf90_inq_varid, nf90_get_var, nf90_open
fielddump calls writestat_nc
initstatsdump calls writestat_dims_nc, mpi_bcast, define_nc, open_nc
checksim calls calccourant, calcdiffnr, chkdiv
advection calls advecc_2nd, advecw_2nd, advecu_2nd, advecc_kappa, advecv_2nd
initmpi calls mpi_wtime, mpi_dims_create, mpi_comm_rank, mpi_comm_size, mpi_cart_shift, mpi_cart_create, mpi_init
initchecksim calls mpi_bcast
tstep_update calls mpi_allreduce
exitmodules calls exitglobal, exitsubgrid, exitthermodynamics, exitmpi, exitpois, exitfields, exitinlet
bottom calls wfuno, wfmneutral
ibmwallfun calls ywallfunplus, zwallfun, ywallfunmin, xwallfun
boundary calls iolet, drivergen, inletgen, inletgennotemp, fluxtopscal, cyclicqj, inlettop, scalrec, fluxtop, valuetopscal, scalsirane, cyclicmj, cyclicmi, iohi, cyclicsi, cyclichj, ioqi, cyclicqi, cyclichi, iosi, valuetop, cyclicsj
startup calls initglobal, createmasks, initpois, initfields, calcfluidvolumes, readinitfiles, checkinitvalues, initthermodynamics, mpi_bcast, createscals, initboundary, initsubgrid, initdriver, initinlet
fixuinf1 calls detfreestream
eb calls gaussji, calclw, mpi_bcast, writestat_2d_nc, matinv4, updategr, writestat_1d_nc, intqh, writestat_nc
initfielddump calls writestat_dims_nc, mpi_bcast, define_nc, open_nc
masscorr calls mpi_bcast
initglobal calls mpi_bcast, float
iolet calls slabsum
drivergen calls writedriverfile
inletgen calls writerestartfiles, enthalpythickness, writeinletfile, wrec, readinletfile, slabsum, tinl, momentumthicknessexp, utav, trec, urec, ttav, uinl, blthicknesst, dispthicknessexp
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
inletgennotemp calls writerestartfiles, writeinletfile, wrec, readinletfile, slabsum, momentumthicknessexp, utav, urec, uinl, blthicknesst, dispthicknessexp
createmasks calls mpi_allreduce, mpi_bcast
cyclicqj calls excjs
inlettop calls slabsumi
closure calls closurebc
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
cyclicmj calls excjs
exitmpi calls mpi_wtime, mpi_comm_free, mpi_finalize
readinitfiles calls thermodynamics, boundary, drivergen, mpi_bcast, calc_halflev, readinletfile, slabsum, randomnize, readrestartfiles, readdriverfile
checkinitvalues calls mpi_bcast, mpi_finalize
diagfld calls fromztop
wfuno calls unoh
detfreestream calls mpi_allreduce
calccourant calls mpi_allreduce
writestat_2d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
define_nc calls nf90_inq_varid, nf90_def_var, nf90_inq_dimid, nchandle_error, nf90_redef, nf90_enddef, nf90_put_att
ywallfunplus calls ywallscalarplus
tkestatsdump calls excjs
updategr calls qsat
tderive calls bcp
advecc_kappa calls rlim
fillps calls bcpup
poisr calls vrfftf, all_all_j2, blktri, vrffti, float, vrfftb, barrou
cyclichj calls excjs
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
initsubgrid calls subgridnamelist
solmpj calls mpi_comm_rank, mpi_comm_size, rfftb, rffti, rfftf, all_all_j, float
calcdiffnr calls mpi_allreduce
chkdiv calls mpi_allreduce
ywallfunmin calls ywallscalarmin
initinlet calls readzincoord, winl, wrec, tinl, utav, trec, urec, ttav, uinl
open_nc calls nf90_inq_varid, nf90_get_var, nf90_open, nf90_def_var, nf90_inq_dimid, nf90_inquire_dimension, nf90_create, nf90_enddef, nf90_sync, nf90_put_att, nf90_def_dim, nf90_inquire
writestat_nc calls writestat_2d_nc, writestat_1d_nc, writestat_3d_nc, writestat_3d_short_nc, writestat_time_nc
bcp calls excj
readzincoord calls mpi_bcast
closurebc calls excjs
nchandle_error calls nf90_strerror
bcpup calls excjs
all_all_j2 calls barrou, mpi_alltoall
writestat_3d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
readinletfile calls excjs, yinterpolate
slabsum calls mpi_allreduce
slabsumi calls mpi_allreduce
writestat_3d_short_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
voutletarea calls mpi_bcast
readrestartfiles calls zinterpolate2d, zinterpolatew1d, zinterpolate1d, zinterpolatet1d
excjs calls mpi_sendrecv
all_all_j calls mpi_alltoall
barrou calls mpi_barrier
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
subgridnamelist calls mpi_bcast
dispthicknessexp calls utav
excj calls mpi_sendrecv