barrou – uDALES
barrou Subroutine
5 statements
Source File
public subroutine barrou()
Arguments
None
Calls
Called by
Contents
Source Code
barrou
Source Code
  subroutine barrou()
    implicit none
    call MPI_BARRIER(comm3d,mpierr)
  return
  end subroutine barrou
Call graph
barrou calls mpi_barrier
all_all_j2 calls barrou
poisr calls barrou, all_all_j2
poisson calls poisr
dalesurban calls poisson