fielddump – uDALES
fielddump Subroutine
22 statements
Source File
public subroutine fielddump()
Uses
modfields
modsurfdata
modglobal
modstat_nc
modmpi
Arguments
None
Calls
Called by
Contents
Source Code
fielddump
Source Code
  subroutine fielddump
    use modfields, only : u0,v0,w0,thl0,qt0,ql0,sv0  !ILS13 21.04.2015 changed to u0 from um  etc
    use modsurfdata,only : thls,qts,thvs
    use modglobal, only : ib,ie,ih,jb,je,jh,ke,kb,kh,rk3step,timee,dt_lim,cexpnr,ifoutput,imax,jmax,&
                          tfielddump, tnextfielddump,nsv, lfielddump
    !use modmpi,    only : myid,cmyid
    !use modsubgriddata, only : ekm,sbshr
    use modstat_nc, only : writestat_nc
    use modmpi, only : myid,cmyid
    implicit none
    real, allocatable :: vars(:,:,:,:)
    integer i,j,k
    integer :: writecounter = 1
    if (.not. (timee>=tnextfielddump)) return
    if (.not. lfielddump) return
    if (rk3step/=3) return
    tnextfielddump=tnextfielddump+tfielddump
   allocate(vars(ib:ie,jb:je,kb:ke,nvar))
    do n=1,nvar
      vars(ib:ie,jb:je,kb:ke,n) = pfields(n)%point
    end do
   call writestat_nc(ncid,1,tncname,(/timee/),nrec,.true.)
   call writestat_nc(ncid,nvar,ncname,vars,nrec,imax,jmax,khigh-klow+1)
   deallocate(vars)
  end subroutine fielddump
Call graph
fielddump calls writestat_nc
writestat_nc calls writestat_2d_nc, writestat_1d_nc, writestat_time_nc, writestat_3d_nc, writestat_3d_short_nc
writestat_2d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_short_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
dalesurban calls fielddump