momentumthicknessexp – uDALES
momentumthicknessexp Subroutine
14 statements
Source File
public subroutine momentumthicknessexp(output, uinput)
Uses
modglobal
modinletdata
modmpi
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: output
real, intent(in), dimension(kb:ke) :: uinput
Called by
Contents
Source Code
momentumthicknessexp
Source Code
  subroutine momentumthicknessexp(output,uinput)
    use modglobal, only : jb,kb,ke,dzf !,Uinf
    use modinletdata, only : ubulk
    use modmpi, only    : myid
    implicit none
       real, dimension(kb:ke), intent(in) :: uinput  !< input velocity
       real, intent(out)                  :: output  !< momentum thickness
       real, dimension(kb:ke)             :: mthick
!       real    :: umax
       integer :: k
!      write(6,*) 'uinletbc(jb,ke),Uinl(ke)=', uinletbc(jb,ke),uinput(ke)
!       umax = maxval(uinput)
       do k=kb,ke
         mthick(k) = ((uinput(k)/uinput(ke)) - (uinput(k)**2. / uinput(ke)**2.) )*dzf(k)
!         mthick(k) = ((uinput(k)/umax) - (uinput(k)**2. / umax**2.))*dzf(k)
       end do
       output   = sum(mthick)  ! momentum thickness
  end subroutine momentumthicknessexp
Call graph
inletgennotemp calls momentumthicknessexp
inletgen calls momentumthicknessexp
boundary calls inletgennotemp, inletgen
readinitfiles calls boundary
dalesurban calls boundary, startup
startup calls readinitfiles