nchandle_error – uDALES
nchandle_error Subroutine
10 statements
Source File
public subroutine nchandle_error(status)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
Calls
Called by
Contents
Source Code
nchandle_error
Source Code
  subroutine nchandle_error(status)
    use netcdf
    implicit none
    integer, intent(in) :: status
    if(status /= nf90_noerr) then
      write(0, *) trim(nf90_strerror(status))
      write(0, *) 'ERROR: status',  status
      stop 1
    end if
  end subroutine nchandle_error
Call graph
nchandle_error calls nf90_strerror
define_nc calls nchandle_error
initstatsdump calls define_nc
initfielddump calls define_nc
initeb calls define_nc
dalesurban calls initstatsdump, initfielddump, initeb