subgrid – uDALES
subgrid Subroutine
19 statements
Source File
public subroutine subgrid()
Uses
modglobal
modfields
modsurfdata
modmpi
Arguments
None
Calls
Called by
Contents
None
Call graph
subgrid calls closure, diffw, diffu, diffv
closure calls closurebc
closurebc calls excjs
excjs calls mpi_sendrecv
dalesurban calls subgrid