writestat_nc – uDALES
writestat_nc Interface
7 statements
Source File
public interface writestat_nc
Calls
Called by
Contents
Module Procedures
writestat_time_nc writestat_1D_nc writestat_2D_nc writestat_3D_nc writestat_3D_short_nc
Module Procedures
public subroutine writestat_time_nc(ncid, nvar, ncname, vars, nrec, lraise)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(nvar) :: vars
integer, intent(inout) :: nrec
logical, intent(in) :: lraise
public subroutine writestat_1D_nc(ncid, nvar, ncname, vars, nrec, dim1)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(dim1,nvar) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
public subroutine writestat_2D_nc(ncid, nvar, ncname, vars, nrec, dim1, dim2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(:,:,:) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
integer, intent(in) :: dim2
public subroutine writestat_3D_nc(ncid, nvar, ncname, vars, nrec, dim1, dim2, dim3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
real, intent(in), dimension(dim1,dim2,dim3,nvar) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
integer, intent(in) :: dim2
integer, intent(in) :: dim3
public subroutine writestat_3D_short_nc(ncid, nvar, ncname, vars, nrec, dim1, dim2, dim3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: nvar
character(len=*), intent(in), dimension(:,:) :: ncname
integer(kind=selected_int_kind(4)), intent(in), dimension(dim1,dim2,dim3,nvar) :: vars
integer, intent(in) :: nrec
integer, intent(in) :: dim1
integer, intent(in) :: dim2
integer, intent(in) :: dim3
Call graph
writestat_nc calls writestat_2d_nc, writestat_1d_nc, writestat_time_nc, writestat_3d_nc, writestat_3d_short_nc
writestat_2d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_short_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
fielddump calls writestat_nc
statsdump calls writestat_nc
eb calls writestat_nc
dalesurban calls fielddump, statsdump, eb